### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by paul-carteron** [kadyb/test#1]
Hi @kadyb,

I'd like to ask you some advices related to the problem you help finding with this repo (which was really helpful !!).
The solution Sys.setenv(GDAL_SKIP="DODS") works but not in my case because I running code inside vignette and environnement variable cant be read. 

The solution I find was using `-- config GDAL_SKIP DODS` directly from gdal_translate but with `sf::gdal_utils` I cannot set config option.

So, do you know if there a way to call `-- config GDAL_SKIP DODS`  from `sf` without environnement variable ? 
If not, I will probably add another dependency to do it like [gdalUtilities](https://cran.r-project.org/web/packages/gdalUtilities/index.html) but are there better options for using gdal in r ?

Thank you in advance for your time

**Comment by kadyb** [comment]
Hi @paul-carteron!

> The solution Sys.setenv(GDAL_SKIP="DODS") works but not in my case because I running code inside vignette and environnement variable cant be read.

It seems the vignette generation works ok (see [test2.Rmd](https://github.com/kadyb/test/blob/main/test2.Rmd) and [workflow](https://github.com/kadyb/test/blob/main/.github/workflows/main.yml)). You probably need to set the environment variable in `rcmdcheck(env = 'GDAL_SKIP="DODS"')`. I tried to run vignettes from your package but something [doesn't work](https://github.com/kadyb/happign/actions/workflows/R-CMD-check.yaml).

> The solution I find was using -- config GDAL_SKIP DODS directly from gdal_translate but with sf::gdal_utils I cannot set config option.

I also tried to do this (unsuccessfully). Probably this is not supported by `sf::gdal_utils()`.

**Comment by paul-carteron** [comment]
Hi @kadyb,
You were right ! I solved the problem by setting `GDAL_SKIP: "DODS"` as environnement variable in my [workflow](https://github.com/paul-carteron/happign/actions/runs/3179677743/workflow).

The vignette you test from my package wasn't working because I was testing other idea.

Thank you so much for you're time and advice !

Have a nice day

**Comment by kadyb** [comment]
Great!
